// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/common.proto

package demopb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CommonMessage with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CommonMessage) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CommonMessage with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CommonMessageMultiError, or
// nil if none found.
func (m *CommonMessage) ValidateAll() error {
	return m.validate(true)
}

func (m *CommonMessage) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return CommonMessageMultiError(errors)
	}

	return nil
}

// CommonMessageMultiError is an error wrapping multiple validation errors
// returned by CommonMessage.ValidateAll() if the designated constraints
// aren't met.
type CommonMessageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CommonMessageMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CommonMessageMultiError) AllErrors() []error { return m }

// CommonMessageValidationError is the validation error returned by
// CommonMessage.Validate if the designated constraints aren't met.
type CommonMessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CommonMessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CommonMessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CommonMessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CommonMessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CommonMessageValidationError) ErrorName() string { return "CommonMessageValidationError" }

// Error satisfies the builtin error interface
func (e CommonMessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCommonMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CommonMessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CommonMessageValidationError{}
