// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.18.1
// source: proto/message_same_pkg.proto

package demopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestSamePkgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32          `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	CommonMessage *CommonMessage `protobuf:"bytes,3,opt,name=common_message,json=commonMessage,proto3" json:"common_message,omitempty"`
}

func (x *TestSamePkgRequest) Reset() {
	*x = TestSamePkgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_message_same_pkg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestSamePkgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestSamePkgRequest) ProtoMessage() {}

func (x *TestSamePkgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_same_pkg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestSamePkgRequest.ProtoReflect.Descriptor instead.
func (*TestSamePkgRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_same_pkg_proto_rawDescGZIP(), []int{0}
}

func (x *TestSamePkgRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestSamePkgRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *TestSamePkgRequest) GetCommonMessage() *CommonMessage {
	if x != nil {
		return x.CommonMessage
	}
	return nil
}

type TestSamePkgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResultCode ResultCode `protobuf:"varint,1,opt,name=result_code,json=resultCode,proto3,enum=test.common.ResultCode" json:"result_code,omitempty"`
	Name       string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age        int32      `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *TestSamePkgResponse) Reset() {
	*x = TestSamePkgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_message_same_pkg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestSamePkgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestSamePkgResponse) ProtoMessage() {}

func (x *TestSamePkgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_same_pkg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestSamePkgResponse.ProtoReflect.Descriptor instead.
func (*TestSamePkgResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_same_pkg_proto_rawDescGZIP(), []int{1}
}

func (x *TestSamePkgResponse) GetResultCode() ResultCode {
	if x != nil {
		return x.ResultCode
	}
	return ResultCode_OK
}

func (x *TestSamePkgResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestSamePkgResponse) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

var File_proto_message_same_pkg_proto protoreflect.FileDescriptor

var file_proto_message_same_pkg_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f,
	0x73, 0x61, 0x6d, 0x65, 0x5f, 0x70, 0x6b, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x74, 0x65, 0x73, 0x74, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x12, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x7d, 0x0a, 0x12, 0x54, 0x65, 0x73, 0x74, 0x53, 0x61, 0x6d, 0x65, 0x50, 0x6b, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x41, 0x0a, 0x0e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x75, 0x0a, 0x13, 0x54, 0x65, 0x73, 0x74, 0x53, 0x61, 0x6d, 0x65, 0x50, 0x6b, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x0a, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x42, 0x11, 0x5a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x67, 0x6f, 0x3b, 0x64, 0x65, 0x6d, 0x6f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_message_same_pkg_proto_rawDescOnce sync.Once
	file_proto_message_same_pkg_proto_rawDescData = file_proto_message_same_pkg_proto_rawDesc
)

func file_proto_message_same_pkg_proto_rawDescGZIP() []byte {
	file_proto_message_same_pkg_proto_rawDescOnce.Do(func() {
		file_proto_message_same_pkg_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_message_same_pkg_proto_rawDescData)
	})
	return file_proto_message_same_pkg_proto_rawDescData
}

var file_proto_message_same_pkg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_message_same_pkg_proto_goTypes = []interface{}{
	(*TestSamePkgRequest)(nil),  // 0: test.message.TestSamePkgRequest
	(*TestSamePkgResponse)(nil), // 1: test.message.TestSamePkgResponse
	(*CommonMessage)(nil),       // 2: test.common.CommonMessage
	(ResultCode)(0),             // 3: test.common.ResultCode
}
var file_proto_message_same_pkg_proto_depIdxs = []int32{
	2, // 0: test.message.TestSamePkgRequest.common_message:type_name -> test.common.CommonMessage
	3, // 1: test.message.TestSamePkgResponse.result_code:type_name -> test.common.ResultCode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_message_same_pkg_proto_init() }
func file_proto_message_same_pkg_proto_init() {
	if File_proto_message_same_pkg_proto != nil {
		return
	}
	file_proto_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_message_same_pkg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestSamePkgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_message_same_pkg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestSamePkgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_message_same_pkg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_message_same_pkg_proto_goTypes,
		DependencyIndexes: file_proto_message_same_pkg_proto_depIdxs,
		MessageInfos:      file_proto_message_same_pkg_proto_msgTypes,
	}.Build()
	File_proto_message_same_pkg_proto = out.File
	file_proto_message_same_pkg_proto_rawDesc = nil
	file_proto_message_same_pkg_proto_goTypes = nil
	file_proto_message_same_pkg_proto_depIdxs = nil
}
