// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/message_no_pkg.proto

package demopb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on TestNoPkgRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *TestNoPkgRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TestNoPkgRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TestNoPkgRequestMultiError, or nil if none found.
func (m *TestNoPkgRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *TestNoPkgRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Age

	if all {
		switch v := interface{}(m.GetCommonMessage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TestNoPkgRequestValidationError{
					field:  "CommonMessage",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TestNoPkgRequestValidationError{
					field:  "CommonMessage",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCommonMessage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TestNoPkgRequestValidationError{
				field:  "CommonMessage",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Test4

	if len(errors) > 0 {
		return TestNoPkgRequestMultiError(errors)
	}

	return nil
}

// TestNoPkgRequestMultiError is an error wrapping multiple validation errors
// returned by TestNoPkgRequest.ValidateAll() if the designated constraints
// aren't met.
type TestNoPkgRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TestNoPkgRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TestNoPkgRequestMultiError) AllErrors() []error { return m }

// TestNoPkgRequestValidationError is the validation error returned by
// TestNoPkgRequest.Validate if the designated constraints aren't met.
type TestNoPkgRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TestNoPkgRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TestNoPkgRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TestNoPkgRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TestNoPkgRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TestNoPkgRequestValidationError) ErrorName() string { return "TestNoPkgRequestValidationError" }

// Error satisfies the builtin error interface
func (e TestNoPkgRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTestNoPkgRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TestNoPkgRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TestNoPkgRequestValidationError{}

// Validate checks the field values on TextNoPkgResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *TextNoPkgResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TextNoPkgResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TextNoPkgResponseMultiError, or nil if none found.
func (m *TextNoPkgResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *TextNoPkgResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ResultCode

	// no validation rules for Name

	// no validation rules for Age

	if len(errors) > 0 {
		return TextNoPkgResponseMultiError(errors)
	}

	return nil
}

// TextNoPkgResponseMultiError is an error wrapping multiple validation errors
// returned by TextNoPkgResponse.ValidateAll() if the designated constraints
// aren't met.
type TextNoPkgResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TextNoPkgResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TextNoPkgResponseMultiError) AllErrors() []error { return m }

// TextNoPkgResponseValidationError is the validation error returned by
// TextNoPkgResponse.Validate if the designated constraints aren't met.
type TextNoPkgResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TextNoPkgResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TextNoPkgResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TextNoPkgResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TextNoPkgResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TextNoPkgResponseValidationError) ErrorName() string {
	return "TextNoPkgResponseValidationError"
}

// Error satisfies the builtin error interface
func (e TextNoPkgResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTextNoPkgResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TextNoPkgResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TextNoPkgResponseValidationError{}
